variables:
  REPOSITORY: registry.timmertech.nl

build:latest:
  stage: build
  only: 
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN ${REPOSITORY}
    - docker build --pull --force-rm=true 
        --build-arg VCS_REF=`git rev-parse --short HEAD` 
        --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` 
        --tag=${REPOSITORY}/${CI_PROJECT_PATH} .
    - docker push ${REPOSITORY}/${CI_PROJECT_PATH}

build:release:
  stage: build
  only:
    - tags
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN ${REPOSITORY}
    - docker build --pull --force-rm=true 
        --build-arg VCS_REF=`git rev-parse --short HEAD` 
        --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` 
        --tag=${REPOSITORY}/${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME} .
    - docker push ${REPOSITORY}/${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}
