#!/usr/bin/with-contenv bash
set -e

# Run in system mode
exec gitlab-runner /usr/bin/gitlab-runner -- run \
		--working-directory ${GITLAB_RUNNER_DATA} \
		--config ${GITLAB_RUNNER_DATA}/config.toml;

# EOF