#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

docker build \
		--build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
		--build-arg VCS_REF="$(git rev-parse --short HEAD)" \
		--build-arg CI_PROJECT_NAME="${CI_PROJECT_NAME}" \
        --build-arg CI_PROJECT_URL="${CI_PROJECT_URL}" \
		--build-arg DOCKER_IMAGE="${IMAGE_NAME}" \
		-t "${IMAGE_NAME}" .

# EOF