#!/usr/bin/env bash

declare -r VERSION="${1}"

docker build \
    --build-arg=DOCKER_IMAGE_BASE=${CI_REGISTRY}/docker/alpine-base-service:latest \
    --build-arg=REMOTE_VERSION="${VERSION}" \
    -t ${CI_REGISTRY}/docker/gitlab-runner:"${VERSION}" \
    .
