#!/usr/bin/env bash
# shellcheck shell=bash

declare -r VERSION="${1}"
declare -r TOKEN="${2}"
declare -r URL="${3}"

docker run \
    --rm \
    --name runner-test \
    -e REGISTRATION_TOKEN="${TOKEN}" \
    -e CI_SERVER_URL="${URL}" \
    -v "${PWD}"/data:/config \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -t ${CI_REGISTRY}/docker/gitlab-runner:"${VERSION}"
