#!/usr/bin/with-contenv bash
set -e

if [ ! -d ${GITLAB_RUNNER_DATA} ]; then
	mkdir -p ${GITLAB_RUNNER_DATA}
fi

if [ -d ${GITLAB_RUNNER_DATA} ]; then
	find ${GITLAB_RUNNER_DATA} -type f -exec chmod 0600 {} \;
	find ${GITLAB_RUNNER_DATA} -type d -exec chmod 0700 {} \;
fi

chown -R gitlab-runner:gitlab-runner ${GITLAB_RUNNER_DATA}

# EOF