#!/usr/bin/with-contenv bash
set -e

CA_CERTIFICATES_PATH=${CA_CERTIFICATES_PATH:-$GITLAB_RUNNER_DATA/certs/ca.crt}

if [[ -f ${CA_CERTIFICATES_PATH} ]]; then
	cp "${CA_CERTIFICATES_PATH}" /usr/local/share/ca-certificates/ca.crt
	update-ca-certificates >/dev/null
fi

# EOF