#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008

mkdir -p /config/{.docker,.ssh,data,certs}

# Setup Password
if [ -n "${SUDO_PASSWORD}" ] || [ -n "${SUDO_PASSWORD_HASH}" ]; then
    echo "setting up sudo access"
    if ! grep -q 'abc' /etc/sudoers; then
        echo "adding abc to sudoers"
        echo "abc ALL=(ALL:ALL) ALL" >> /etc/sudoers
    fi
    if [ -n "${SUDO_PASSWORD_HASH}" ]; then
        echo "setting sudo password using sudo password hash"
        sed -i "s|^abc:\!:|abc:${SUDO_PASSWORD_HASH}:|" /etc/shadow
    else
        echo "setting sudo password using SUDO_PASSWORD env var"
        echo -e "${SUDO_PASSWORD}\n${SUDO_PASSWORD}" | passwd abc
    fi
fi

# Permissions
if [ -f "/usr/bin/find" ] && [ -f "/usr/bin/xargs" ]; then
    # Split workload between config and workspace
    echo "setting permissions::configuration"
    CORES=$(nproc --all)
    find /config -maxdepth 4 -mindepth 1 -path /config/data -prune -false -o -type d -print0 | \
        xargs -0 -r --max-args=1 --max-procs=$((CORES*2*8)) \
        chown -R abc:abc

    BG=""
    if [ -n "${CHOWN_BACKGROUND}" ]; then
        echo "setting permissions::workspace (Background)"
        BG="&"
    else
        echo "setting permissions::workspace"
    fi

    chown abc:abc /config/data
    find /config/data -maxdepth 4 -mindepth 1 -type d -print0 | \
        xargs -0 -r --max-args=1 --max-procs=$((CORES*2*16)) \
        chown -R abc:abc ${BG}

else
    chown -R abc:abc
        /config
fi
