#!/usr/bin/with-contenv bash
set -e

if [ -S /var/run/docker.sock ]; then
	echo -n "  Configuring Docker Socket..."
	
	DOCKER_SOCKET_GID=$(stat -c %g  /var/run/docker.sock)
	DOCKER_SOCKET_GROUP=$(stat -c %G /var/run/docker.sock)
	
	if [[ ${DOCKER_SOCKET_GROUP} == "UNKNOWN" ]]; then
		DOCKER_SOCKET_GROUP=docker
		groupadd -g ${DOCKER_SOCKET_GID} ${DOCKER_SOCKET_GROUP}
	fi
	
	usermod -a -G ${DOCKER_SOCKET_GROUP} gitlab-runner
	echo " [DONE]"
fi

# EOF