#!/usr/bin/with-contenv bash
set -e

GITLAB_TIMEOUT=${GITLAB_TIMEOUT:-600}

echo -n "  Waiting for GitLab"
while [ $(curl -I -sL -w '%{http_code}\n' "${CI_SERVER_URL}" -o /dev/null) -ne 200 ]
do
	GITLAB_TIMEOUT=$(expr ${GITLAB_TIMEOUT} - 5)
	if [[ ${GITLAB_TIMEOUT} -eq 0 ]]; then
		echo " [TIMEOUT]"
		exit 1
	fi
	echo -n "."
	sleep 5
done
echo " [READY]"

# EOF