#!/usr/bin/with-contenv bash
set -e

RUNNER_EXECUTOR=${RUNNER_EXECUTOR:-shell}
RUNNER_NAME=${RUNNER_NAME:-gitlab-runner}

DOCKER_IMAGE=${DOCKER_IMAGE:-docker:latest}

if [[ ! -e ${GITLAB_RUNNER_DATA}/config.toml ]]; then
	if [[ -n ${CI_SERVER_URL} && -n ${REGISTRATION_TOKEN} && -n ${RUNNER_NAME} && -n ${RUNNER_EXECUTOR} ]]; then
		gitlab-runner register --non-interactive --config ${GITLAB_RUNNER_DATA}/config.toml
	else
		echo "Missing Required environment variable(s)"
	fi
fi

# EOF