#!/usr/bin/with-contenv bash
set -e

RUNNER_EXECUTOR=${RUNNER_EXECUTOR:-shell}
RUNNER_DESCRIPTION=${RUNNER_DESCRIPTION:-gitlab-runner}
RUNNER_DOCKER_IMAGE=${RUNNER_DOCKER_IMAGE:-docker:latest}

DOCKER_IMAGE=${DOCKER_IMAGE:-docker:latest}

if [[ ! -e ${GITLAB_RUNNER_DATA}/config.toml ]]; then
	if [[ -n ${CI_SERVER_URL} && -n ${RUNNER_TOKEN} && -n ${RUNNER_DESCRIPTION} && -n ${RUNNER_EXECUTOR} ]]; then
		if [[ "${RUNNER_EXECUTOR}" == "docker" ]];then
			if [[ -n ${RUNNER_DOCKER_IMAGE} ]];then
				RUNNER_DOCKER_ARGS="--docker-image ${RUNNER_DOCKER_IMAGE}"
			fi
		fi
		sudo -HEu gitlab-runner \
		gitlab-runner register --config ${GITLAB_RUNNER_DATA}/config.toml \
		-n -u "${CI_SERVER_URL}" -r "${RUNNER_TOKEN}" --name "${RUNNER_DESCRIPTION}" --executor "${RUNNER_EXECUTOR}" ${RUNNER_DOCKER_ARGS}
	else
		echo "Missing Required Parameter"
	fi
else
	sudo -HEu gitlab-runner gitlab-runner register --config ${GITLAB_RUNNER_DATA}/config.toml
fi

# EOF