#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008

if [[ ! -e /config/.ssh/id_rsa || ! -e $/config/.ssh/id_rsa.pub ]]; then
	echo -n "  Generating SSH deploy keys..."
	rm -rf /config/.ssh/id_rsa /config/.ssh/id_rsa.pub
	ssh-keygen -t rsa -N "" -f /config/.ssh/id_rsa
	echo " [DONE]"
fi

echo -n "Setting SSH Permissions..."
chmod 600 /config/.ssh/id_rsa /config/.ssh/id_rsa.pub
chmod 700 /config/.ssh
echo " [DONE]"

echo -n "Your SSH deploy key is: "
cat /config/.ssh/id_rsa.pub
echo ""

# EOF