#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e

RUNNER_EXECUTOR=${RUNNER_EXECUTOR:-shell}
RUNNER_NAME=${RUNNER_NAME:-gitlab-runner}
DOCKER_IMAGE=${DOCKER_IMAGE:-docker:latest}

if [ -z "${REGISTRATION_TOKEN}" ]; then
	echo "Missing Required environment variable: '\$REGISTRATION_TOKEN'"
	exit 1
fi

if [[ ! -e /config/config.toml ]]; then
	if [[ -n ${CI_SERVER_URL} && -n ${REGISTRATION_TOKEN} && -n ${RUNNER_NAME} && -n ${RUNNER_EXECUTOR} ]]; then
		gitlab-runner register --non-interactive --config /config/config.toml
	else
		echo "Missing Required environment variable(s)"
	fi
fi

# EOF